### ISSUE TITLE
Failed to install via pip on M1 Mac

### ISSUE THREAD

**Issue by BolunDai0216** [DanielBok/nlopt-python#13]
Hi,

I was trying to install this on an M1 Macbook and got the following error

```
>> python3 -m pip install nlopt
Defaulting to user installation because normal site-packages is not writeable
Collecting nlopt
  Using cached nlopt-2.6.2.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14 in ./Library/Python/3.8/lib/python/site-packages (from nlopt) (1.22.3)
Building wheels for collected packages: nlopt
  Building wheel for nlopt (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 20, in run
          subp.check_call(["cmake", "--version"])
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 85, in <module>
          setup(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 22, in run
          raise RuntimeError(
      RuntimeError: CMake must be installed to build the following extensions: nlopt._nlopt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nlopt
  Running setup.py clean for nlopt
Failed to build nlopt
Installing collected packages: nlopt
  Running setup.py install for nlopt ... error
  error: subprocess-exited-with-error

  × Running setup.py install for nlopt did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running install
      running build
      running build_ext
      Traceback (most recent call last):
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 20, in run
          subp.check_call(["cmake", "--version"])
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 85, in <module>
          setup(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 561, in run
          self.run_command('build')
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/rq/md19ny9502q_prjm4sf7n0gr0000gn/T/pip-install-ynkm37uw/nlopt_3e9fdc684b594d41941ed4415a8337cd/setup.py", line 22, in run
          raise RuntimeError(
      RuntimeError: CMake must be installed to build the following extensions: nlopt._nlopt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> nlopt

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Is this an issue with the M1 mac or something else. Is it possible to help me take a look at this?

Thanks in advance!

**Comment by romanWSgit** [comment]
I am having the same issue on an M1 Mac. Haven't found any solution yet.

**Comment by joamatab** [comment]
conda install nlopt also works

How can we fix the pypi install for M1?


see https://github.com/flexcompute/tidy3d/issues/441

**Comment by defencedog** [comment]
I was successfull on Android ARM64 Termux Python3.9
@ https://github.com/stevengj/nlopt/issues/478#issuecomment-1312962575

**Comment by hakonanes** [comment]
I see a similar error on mac with M3.

**Comment by hf-krechan** [comment]
I have the same issue and it would be great if we can solve this issue.
GitHub has now runners for ARM architecture.
In the `cadquery` repository they use also a GitHub action to build wheels for macOS-arm64.

https://github.com/CadQuery/ocp-build-system/pull/22/files

**Comment by hf-krechan** [comment]
Just in case if someone like does also not know about `miniforge`.
Miniforge is a minimal installer for the Conda package manager. And with this you can install `nlopt` on a M1 machine.


## Install Miniforge 

You can install it with
```bash
brew install --cask miniforge
```

After the installation you need to run
```bash
conda init "$(basename "${SHELL}")"
```

## Create a Conda Environment

Instead of using `venv` you use `conda` to create a virtual environment.
```bash
conda create --name myenv python=3.11
```
Python 3.11 is the latest version at the moment.
I guess it is necessary that you have Python 3.11 installed already.

Activate the conda environment with

```bash
conda activate myenv
```

Now you can install `nlopt` with

```bash
conda install nlopt
```

If you need a package which is not available in the conda repositories, you can still use `pip`.
But be careful with this approach, it can easily lead to version conflicts.
