### ISSUE TITLE
On armv8l Compile Error at 100%

### ISSUE THREAD

**Issue by defencedog** [DanielBok/nlopt-python#27]
I did `pip install nlopt -v` following is partial output

```
[ 94%] Building CXX object extern/nlopt/CMakeFiles/nlopt.dir/src/algs/ags/ags.cc.o
  [ 96%] Linking CXX static library libnlopt.a
  [100%] Built target nlopt
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/data/data/com.termux/files/usr/tmp/pip-install-vbohu2l6/nlopt_f25797d0023d4d56b2dd14e0e1bb29ee/setup.py", line 85, in <module>
      setup(
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/data/data/com.termux/files/usr/tmp/pip-install-vbohu2l6/nlopt_f25797d0023d4d56b2dd14e0e1bb29ee/setup.py", line 28, in run
      self.build_extension(ext)
    File "/data/data/com.termux/files/usr/tmp/pip-install-vbohu2l6/nlopt_f25797d0023d4d56b2dd14e0e1bb29ee/setup.py", line 70, in build_extension
      nlopt_py = next(Path(self.build_temp).rglob("nlopt.py"))
  StopIteration
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/data/com.termux/files/usr/bin/python3.9 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/data/data/com.termux/files/usr/tmp/pip-install-vbohu2l6/nlopt_f25797d0023d4d56b2dd14e0e1bb29ee/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-y_fnr7vl
  cwd: /data/data/com.termux/files/usr/tmp/pip-install-vbohu2l6/nlopt_f25797d0023d4d56b2dd14e0e1bb29ee/
  Building wheel for nlopt (setup.py) ... error
  ERROR: Failed building wheel for nlopt
  Running setup.py clean for nlopt
  Running command python setup.py clean
  running clean
  removing 'build/temp.linux-armv8l-3.9' (and everything under it)
  'build/lib.linux-armv8l-3.9' does not exist -- can't clean it
  'build/bdist.linux-armv8l' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing 'build'
Failed to build nlopt
ERROR: Could not build wheels for nlopt, which is required to install pyproject.toml-based projects

```

**Comment by defencedog** [comment]
`pip` didn't provide any meaningful error cause. When I compiled via source code `git clone --recursive` & then issued `python setup.py bdist_wheel` it throwed error about missing `swig` ...After installing it everything works fine
